const contactData = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "9999999999",
    subject: "Inquiry about services",
    message: "I would like to know more about your offerings. Specifically, I am interested in learning about the range of services you provide, your pricing models, and how your solutions can help my business improve its operations. Could you also provide any case studies or references that showcase how other companies have benefited from your services?",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "5555678123",
    subject: "Partnership Proposal",
    message: "Let's discuss a potential partnership. I believe that by working together, we can create mutually beneficial solutions for our clients. Our companies share a similar mission, and I am confident that by combining our strengths, we can offer enhanced value to the market. I'd like to set up a meeting to explore how we can collaborate effectively.",
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    phone: "5558765432",
    subject: "Support Request",
    message: "I'm having an issue with my account. Specifically, I am unable to access my account dashboard after logging in. I have tried resetting my password and clearing my browser cache, but the issue persists. Can you please assist me in resolving this as soon as possible? I have urgent tasks I need to complete using your platform.",
  },
  {
    id: 4,
    name: "Bob Brown",
    email: "bob.brown@example.com",
    phone: "5554321987",
    subject: "Billing Question",
    message: "Can you clarify the recent charge on my account? I noticed a charge that I do not recognize, and I would like to understand what it is for. Could you provide me with a detailed invoice and explain any additional fees or charges that may have been applied to my account? I need this information for my records.",
  },
  {
    id: 5,
    name: "Chris Green",
    email: "chris.green@example.com",
    phone: "5553456789",
    subject: "Request for Information",
    message: "I need more details about your product. Specifically, I am looking for technical specifications, integration options, and any available documentation that outlines how your product works. Could you also provide information on the pricing structure for the different tiers or packages that you offer?",
  },
  {
    id: 6,
    name: "Emma White",
    email: "emma.white@example.com",
    phone: "5559876543",
    subject: "Service Feedback",
    message: "Great service! Keep up the good work. I wanted to let you know how much I appreciate the prompt and professional assistance I received from your support team. They helped resolve my issue quickly and efficiently, and I am very satisfied with the overall experience. I will definitely recommend your services to others.",
  },
  {
    id: 7,
    name: "David Blue",
    email: "david.blue@example.com",
    phone: "5556543210",
    subject: "Feature Request",
    message: "It would be great if you could add this feature. I am specifically requesting an enhancement to the reporting functionality, where users can export data in various formats like CSV, Excel, and PDF. Having this feature would allow me to analyze the data more effectively and share insights with my team.",
  },
  {
    id: 8,
    name: "Sophia Black",
    email: "sophia.black@example.com",
    phone: "5559087654",
    subject: "Issue with Login",
    message: "I am unable to log into my account. Every time I try, I receive an error message that says my credentials are invalid, even though I have double-checked my username and password. I've also tried resetting my password, but the problem persists. Could you please look into this issue and help me regain access?",
  },
  {
    id: 9,
    name: "Liam Grey",
    email: "liam.grey@example.com",
    phone: "5553210987",
    subject: "Request for Demo",
    message: "Could you schedule a demo for us? Our team is interested in seeing how your platform works and how it can integrate with our current systems. We would like to see a walkthrough of the key features, as well as a discussion on how your solution can address our specific business needs.",
  },
  {
    id: 10,
    name: "Mia Gold",
    email: "mia.gold@example.com",
    phone: "5557890123",
    subject: "Order Status",
    message: "Can you provide an update on my recent order? I placed an order two weeks ago and have not yet received a confirmation or shipment notification. I would like to know the current status of my order and when I can expect it to be delivered. Please let me know if there are any delays or issues with my order.",
  },
 
];

export default contactData;
